# Generated by Django 4.2 on 2023-04-26 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "brand",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Laptops", "Laptops"),
                            ("Arts", "Arts"),
                            ("Food", "Food"),
                            ("Clothing", "Clothing"),
                            ("Home", "Home"),
                            ("Kitchen", "Kitchen"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ratings",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="products"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="products"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="products"),
                ),
                ("stock", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products2",
                "ordering": ["-created_at"],
            },
        ),
    ]
